version: "3.3"
services:
  # Contenedor A.
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    env_file:
      - '.env'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_INITDB_PORT: ${MONGO_PORT}
    volumes:
      - ./contenedor-a/mongo-volume:/data/db
    ports:
      - '27017:27017'
  # Contenedor B.
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    env_file:
      - '.env'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
    links:
      - 'mongo'
    depends_on:
      - 'mongo'
  # Contenedor C.
  scraper:
    container_name: scraper
    build: './contenedor-c/'
    restart: 'on-failure:10'
    env_file:
      - '.env'
    depends_on:
      - 'mongo'
  # Contenedor D.
  nodeapi:
    container_name: nodeapi
    image: nodejs:latest
    restart: unless-stopped
    build:
      context: ./contenedor-d/.
      dockerfile: Dockerfile
    env_file: .env
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB} 
    ports:
      - "1337:1337"
    links:
      - 'mongo'
    depends_on:
      - 'mongo'
  # Contenedor E.
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    env_file:
      - '.env'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'
  # Contenedor F.
  apache:
    container_name: apache
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./contenedor-f/build/:/app
    links:
      - 'nodeapi'
    # Contenedor G.
    #noderabbit:
    #  container_name: noderabbit
    #  image: nodejs:latest
    #  restart: unless-stopped
    #  build:
    #    context: ./contenedor-g/.
    #    dockerfile: Dockerfile
    #  env_file: .env
    #  environment:
    #    MONGO_USERNAME: ${MONGO_USERNAME}
    #    MONGO_PASSWORD: ${MONGO_PASSWORD}
    #    MONGO_HOSTNAME: ${MONGO_HOSTNAME}
    #    MONGO_PORT: ${MONGO_PORT}
    #    MONGO_DB: ${MONGO_DB} 
    #  links:
    #    - 'mongo'